"""Compile-time renderer for the /loxone/ config-template endpoint.

The `template:` block on the `loxone:` component is purely descriptive - it
generates no runtime send/receive code. It is turned into three static bodies
(an HTML index plus two Loxone Config templates) that the device serves so you
can import matching Virtual Inputs / Outputs into Loxone Config in a few clicks.
"""

import html
from xml.sax.saxutils import quoteattr

import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.core import CORE

CONF_TEMPLATE = "template"
CONF_TITLE = "title"
CONF_INPUTS = "inputs"
CONF_OUTPUTS = "outputs"
CONF_COMMAND = "command"
CONF_ANALOG = "analog"
CONF_MIN = "min"
CONF_MAX = "max"

_ITEM_SCHEMA = cv.Schema(
    {
        cv.Required(CONF_COMMAND): cv.string_strict,
        cv.Optional(CONF_ANALOG, default=False): cv.boolean,
        cv.Optional(CONF_MIN, default=0): cv.float_,
        cv.Optional(CONF_MAX, default=1): cv.float_,
    }
)

TEMPLATE_SCHEMA = cv.Schema(
    {
        cv.Optional(CONF_TITLE): cv.string,
        cv.Optional(CONF_INPUTS, default=[]): cv.ensure_list(_ITEM_SCHEMA),
        cv.Optional(CONF_OUTPUTS, default=[]): cv.ensure_list(_ITEM_SCHEMA),
    }
)


def _num(value: float) -> str:
    """Render a schema float without a trailing .0 when it is integral."""
    return str(int(value)) if float(value).is_integer() else repr(float(value))


def _a(value) -> str:
    """A value quoted for use as an XML attribute."""
    return quoteattr(str(value))


def _loxone_escape(delimiter: str) -> str:
    """Device delimiter as Loxone Config command-text escapes (\\n, \\r, \\t)."""
    return (
        delimiter.replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def _build_inputs_xml(title: str, loxone_port: int, items) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<VirtualInUdp Title={_a(title)} Comment={_a('Generated by esphome-loxone')} "
        f'Address="" Port={_a(loxone_port)}>',
        '\t<Info templateType="1" minVersion="15031213"/>',
    ]
    for it in items:
        cmd = it[CONF_COMMAND]
        lo, hi = _num(it[CONF_MIN]), _num(it[CONF_MAX])
        analog = "true" if it[CONF_ANALOG] else "false"
        lines.append(
            f"\t<VirtualInUdpCmd Title={_a(cmd)} Comment=\"\" Address=\"\" "
            f"Check={_a(cmd + ' \\v')} Signed=\"true\" Analog={_a(analog)} "
            f"SourceValLow={_a(lo)} DestValLow={_a(lo)} "
            f"SourceValHigh={_a(hi)} DestValHigh={_a(hi)} "
            f"DefVal=\"0\" MinVal={_a(lo)} MaxVal={_a(hi)} Unit=\"&lt;v&gt;\" HintText=\"\"/>"
        )
    lines.append("</VirtualInUdp>")
    return "\n".join(lines) + "\n"


def _build_outputs_xml(title: str, listen_port: int, delimiter: str, items) -> str:
    term = _loxone_escape(delimiter)
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<VirtualOut Title={_a(title)} Comment={_a('Generated by esphome-loxone')} "
        f'Address={_a(f"/dev/udp/{{IP}}/{listen_port}")} CmdInit="" CloseAfterSend="true">',
        '\t<Info templateType="3" minVersion="15031213"/>',
    ]
    for it in items:
        cmd = it[CONF_COMMAND]
        if it[CONF_ANALOG]:
            lo, hi = _num(it[CONF_MIN]), _num(it[CONF_MAX])
            lines.append(
                f"\t<VirtualOutCmd Title={_a(cmd)} Comment=\"\" "
                f"CmdOnMethod=\"\" CmdOffMethod=\"\" "
                f"CmdOn={_a(f'{cmd} <v>{term}')} CmdOff=\"\" "
                f"CmdOnHTTP=\"\" CmdOffHTTP=\"\" CmdOnPost=\"\" CmdOffPost=\"\" CmdAnswer=\"\" "
                f"HintText=\"\" Analog=\"true\" Repeat=\"0\" RepeatRate=\"0\" "
                f"SourceValLow={_a(lo)} SourceValHigh={_a(hi)} "
                f"DestValLow={_a(lo)} DestValHigh={_a(hi)}/>"
            )
        else:
            lines.append(
                f"\t<VirtualOutCmd Title={_a(cmd)} Comment=\"\" "
                f"CmdOnMethod=\"\" CmdOffMethod=\"\" "
                f"CmdOn={_a(f'{cmd} 1{term}')} CmdOff={_a(f'{cmd} 0{term}')} "
                f"CmdOnHTTP=\"\" CmdOffHTTP=\"\" CmdOnPost=\"\" CmdOffPost=\"\" CmdAnswer=\"\" "
                f"HintText=\"\" Analog=\"false\" Repeat=\"0\" RepeatRate=\"0\"/>"
            )
    lines.append("</VirtualOut>")
    return "\n".join(lines) + "\n"


def _publish_snippet(loxone_id: str, items) -> str:
    if not items:
        return "# (no inputs declared)"
    out = [
        "# device -> Loxone : call send_string_data() whenever the source entity changes.",
        "# Bind each block to your real entity id; `x` is that entity's new state.",
        "",
    ]
    for it in items:
        cmd = it[CONF_COMMAND]
        if it[CONF_ANALOG]:
            expr = f'str_sprintf("%.2f", x)'
            hint = "on_value:  # numeric sensor"
        else:
            expr = 'std::string(x ? "1" : "0")'
            hint = "on_state:  # binary_sensor / switch"
        out += [
            f"# --- {cmd} ---",
            f"# {hint}",
            f'#   - lambda: \'id({loxone_id}).send_string_data("{cmd} " + {expr});\'',
            "",
        ]
    return "\n".join(out).rstrip()


def _command_snippet(loxone_id: str, items) -> str:
    if not items:
        return "# (no outputs declared)"
    body = [
        "loxone:",
        f"  id: {loxone_id}",
        "  # ...existing keys...",
        "  on_string_data:",
        "    - lambda: |-",
    ]
    for it in items:
        cmd = it[CONF_COMMAND]
        prefix = f"{cmd} "
        n = len(prefix)
        body.append(f'        if (data.rfind("{prefix}", 0) == 0) {{')
        if it[CONF_ANALOG]:
            body.append(f"          float v = atof(data.substr({n}).c_str());")
            body.append(f"          // TODO: use `v` ({_num(it[CONF_MIN])}..{_num(it[CONF_MAX])})")
        else:
            body.append(f'          bool on = data.substr({n}) == "1";')
            body.append("          // TODO: act on `on`")
        body.append("        }")
    return "\n".join(body)


def _build_index_html(
    title, loxone_id, loxone_ip, loxone_port, listen_port, delimiter, inputs, outputs
) -> str:
    esc = html.escape
    pub = esc(_publish_snippet(loxone_id, inputs))
    cmd = esc(_command_snippet(loxone_id, outputs))
    in_rows = "".join(
        f"<li><code>{esc(i[CONF_COMMAND])}</code> "
        f"&rarr; <code>{esc(i[CONF_COMMAND])} &lt;{'value' if i[CONF_ANALOG] else '0|1'}&gt;{esc(delimiter.replace(chr(10), chr(92) + 'n'))}</code></li>"
        for i in inputs
    ) or "<li><em>none</em></li>"
    out_rows = "".join(
        f"<li><code>{esc(o[CONF_COMMAND])}</code> "
        f"({'analog ' + _num(o[CONF_MIN]) + '..' + _num(o[CONF_MAX]) if o[CONF_ANALOG] else 'digital'})</li>"
        for o in outputs
    ) or "<li><em>none</em></li>"
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Loxone templates &middot; {esc(title)}</title>
<style>
 body{{font:14px/1.5 system-ui,sans-serif;max-width:52rem;margin:2rem auto;padding:0 1rem;color:#1b1b1b}}
 h1{{font-size:1.3rem}} h2{{font-size:1.05rem;margin-top:2rem}}
 a.btn{{display:inline-block;margin:.25rem .5rem .25rem 0;padding:.5rem .9rem;background:#1462c8;color:#fff;border-radius:6px;text-decoration:none}}
 code{{background:#f0f0f0;padding:.1rem .3rem;border-radius:3px}}
 pre{{background:#f6f8fa;padding:1rem;border-radius:6px;overflow-x:auto;white-space:pre}}
 table{{border-collapse:collapse}} td{{padding:.15rem .6rem .15rem 0;vertical-align:top}}
 @media(prefers-color-scheme:dark){{body{{background:#161616;color:#e6e6e6}}code,pre{{background:#242424}}}}
</style></head><body>
<h1>Loxone Config templates &ndash; {esc(title)}</h1>
<p>Generated by <code>esphome-loxone</code>. Download, then in Loxone Config import under
<em>Virtual Inputs</em> / <em>Virtual Outputs</em> &rarr; <em>Import Template</em>.</p>

<p>
 <a class="btn" href="/loxone/inputs.xml" download>&#8681; inputs.xml (Virtual UDP Input)</a>
 <a class="btn" href="/loxone/outputs.xml" download>&#8681; outputs.xml (Virtual Output, UDP)</a>
</p>

<table>
<tr><td>Miniserver</td><td><code>{esc(loxone_ip)}:{loxone_port}</code> (device sends here)</td></tr>
<tr><td>This device</td><td><code>{{IP}}:{listen_port}</code> UDP (Loxone sends here &mdash; used in outputs.xml)</td></tr>
</table>

<h2>Device &rarr; Loxone ({len(inputs)})</h2>
<ul>{in_rows}</ul>

<h2>Loxone &rarr; device ({len(outputs)})</h2>
<ul>{out_rows}</ul>

<h2>Matching ESPHome config</h2>
<p>The firmware does not send or receive these on its own &mdash; wire them in your YAML:</p>
<pre>{pub}</pre>
<pre>{cmd}</pre>
</body></html>
"""


def add_template_code(config, var):
    tmpl = config[CONF_TEMPLATE]
    title = tmpl.get(CONF_TITLE) or CORE.friendly_name or CORE.name
    loxone_id = str(config["id"])
    loxone_ip = str(config["loxone_ip"])
    loxone_port = int(config["loxone_port"])
    listen_port = int(config["listen_port"])
    delimiter = config["delimiter"]
    inputs = tmpl[CONF_INPUTS]
    outputs = tmpl[CONF_OUTPUTS]

    index_html = _build_index_html(
        title, loxone_id, loxone_ip, loxone_port, listen_port, delimiter, inputs, outputs
    )
    inputs_xml = _build_inputs_xml(title, loxone_port, inputs)
    outputs_xml = _build_outputs_xml(title, listen_port, delimiter, outputs)

    cg.add(var.set_loxone_template(index_html, inputs_xml, outputs_xml))
